import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _currentLang = 'en';
  String get currentLang => _currentLang;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString('ui_lang') ?? 'en';
    notifyListeners();
  }

  Future<void> changeLanguage(String lang) async {
    _currentLang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('ui_lang', lang);
    notifyListeners();
  }

  static const _translations = {
    'en': {
      'home': 'Home',
      'history': 'History',
      'profile': 'Profile',
      'recent_scans': 'Recent Scans',
      'see_all': 'See all',
      'scan_leaf': 'Scan Leaf',
      'disease_info': 'Disease Info',
      'crop_tips': 'Crop Tips',
      'edit_profile': 'Edit Profile',
      'language': 'Language',
      'notifications': 'Notifications',
      'location': 'Location',
      'offline_mode': 'Offline Mode',
      'log_out': 'Log Out',
      'diagnosis': 'Diagnosis',
      'symptoms': 'Symptoms',
      'treatment': 'Treatment',
      'prevention': 'Prevention',
      'take_photo': 'Take Photo & Diagnose',
      'gallery': 'Gallery',
      'scans_done': 'Scans Done',
      'crops_helped': 'Crops Helped',
      'crops_grown': 'Crops Grown',
      'my_crops': 'My Crops',
      'status': 'Status',
      'healthy': 'Healthy',
      'diseased': 'Diseased',
      'unknown': 'Unknown',
          'rate_app': 'Rate PlantGuard',
      'rate_app_sub': 'Help farmers everywhere',
      'privacy_data': 'Privacy & Data',
      'privacy_data_sub': 'Photos never leave your phone',
      'about_app': 'About PlantGuard',
      'about_app_sub': 'v1.0.0 • DeepCognix AI Labs',
      'offline_mode_sub': 'AI runs on-device • no internet',
      'notif_sub': 'Disease & weather alerts',
      'location_label': 'Location',
      'offline_title': 'Offline Mode',
      'offline_desc': 'PlantGuard works fully offline using the on-device TFLite AI model. Your data never leaves your phone.',
      'rate_title': 'Enjoying PlantGuard?',
      'rate_desc': 'Please rate us on the Play Store to help more farmers!',
      'privacy_title': 'Privacy & Data',
      'privacy_desc': 'All scans are processed on-device. Photos are never uploaded without your consent. Scan history is stored only on this device and your account.',
      'about_title': 'About PlantGuard',
      'about_desc': 'PlantGuard v1.0.0 uses AI to detect plant diseases in real time. Built for Indian farmers with 38+ disease classes across 14 crop types.',
      'close': 'Close',
      'go_rate': 'Rate Now',
},
    'hi': {
      'home': 'होम',
      'history': 'इतिहास',
      'profile': 'प्रोफ़ाइल',
      'recent_scans': 'हाल के स्कैन',
      'see_all': 'सभी देखें',
      'scan_leaf': 'पत्ती स्कैन करें',
      'disease_info': 'रोग की जानकारी',
      'crop_tips': 'फसल टिप्स',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'location': 'स्थान',
      'offline_mode': 'ऑफलाइन मोड',
      'log_out': 'लॉग आउट',
      'diagnosis': 'निदान',
      'symptoms': 'लक्षण',
      'treatment': 'उपचार',
      'prevention': 'रोकथाम',
      'take_photo': 'फोटो लें और निदान करें',
      'gallery': 'गैलरी',
      'scans_done': 'कुल स्कैन',
      'crops_helped': 'मदद की गई फसलें',
      'crops_grown': 'उगाई गई फसलें',
      'my_crops': 'मेरी फसलें',
      'status': 'स्थिति',
      'healthy': 'स्वस्थ',
      'diseased': 'रोगग्रस्त',
      'unknown': 'अज्ञात',
          'rate_app': 'PlantGuard को रेट करें',
      'rate_app_sub': 'किसानों की मदद करें',
      'privacy_data': 'गोपनीयता और डेटा',
      'privacy_data_sub': 'फोटो आपके फोन से बाहर नहीं जाते',
      'about_app': 'PlantGuard के बारे में',
      'about_app_sub': 'v1.0.0 • DeepCognix AI Labs',
      'offline_mode_sub': 'ऑन-डिवाइस AI • इंटरनेट की जरूरत नहीं',
      'notif_sub': 'रोग और मौसम अलर्ट',
      'location_label': 'स्थान',
      'offline_title': 'ऑफलाइन मोड',
      'offline_desc': 'PlantGuard पूरी तरह ऑफलाइन काम करता है। आपका डेटा आपके फोन से बाहर नहीं जाता।',
      'rate_title': 'PlantGuard पसंद है?',
      'rate_desc': 'Play Store पर रेटिंग दें और अधिक किसानों की मदद करें!',
      'privacy_title': 'गोपनीयता और डेटा',
      'privacy_desc': 'सभी स्कैन ऑन-डिवाइस प्रोसेस होते हैं। फोटो आपकी अनुमति के बिना अपलोड नहीं होते।',
      'about_title': 'PlantGuard के बारे में',
      'about_desc': 'PlantGuard v1.0.0 AI से पौधों की बीमारी पहचानता है। 14 फसलों में 38+ बीमारियां।',
      'close': 'बंद करें',
      'go_rate': 'रेट करें',
},
    'mr': {
      'home': 'होम',
      'history': 'इतिहास',
      'profile': 'प्रोफाईल',
      'recent_scans': 'अलीकडील स्कॅन',
      'see_all': 'सर्व पहा',
      'scan_leaf': 'पान स्कॅन करा',
      'disease_info': 'रोगाची माहिती',
      'crop_tips': 'पीक टिप्स',
      'edit_profile': 'प्रोफाईल संपादित करा',
      'language': 'भाषा',
      'notifications': 'सूचना',
      'location': 'स्थान',
      'offline_mode': 'ऑफलाईन मोड',
      'log_out': 'लॉग आउट',
      'diagnosis': 'निदान',
      'symptoms': 'लक्षणे',
      'treatment': 'उपचार',
      'prevention': 'प्रतिबंध',
      'take_photo': 'फोटो घ्या आणि निदान करा',
      'gallery': 'गॅलरी',
      'scans_done': 'केलेले स्कॅन',
      'crops_helped': 'मदद केलेली पिके',
      'crops_grown': 'लागवड केलेली पिके',
      'my_crops': 'माझी पिके',
      'status': 'स्थिती',
      'healthy': 'निरोगी',
      'diseased': 'रोगट',
      'unknown': 'अज्ञात',
          'rate_app': 'PlantGuard ला रेटिंग द्या',
      'rate_app_sub': 'शेतकऱ्यांना मदत करा',
      'privacy_data': 'गोपनीयता आणि डेटा',
      'privacy_data_sub': 'फोटो आपल्या फोनबाहेर जात नाहीत',
      'about_app': 'PlantGuard बद्दल',
      'about_app_sub': 'v1.0.0 • DeepCognix AI Labs',
      'offline_mode_sub': 'ऑन-डिव्हाइस AI • इंटरनेट लागत नाही',
      'notif_sub': 'रोग आणि हवामान अलर्ट',
      'location_label': 'स्थान',
      'offline_title': 'ऑफलाइन मोड',
      'offline_desc': 'PlantGuard पूर्णपणे ऑफलाइन काम करतो. आपला डेटा फोनबाहेर जात नाही.',
      'rate_title': 'PlantGuard आवडतो का?',
      'rate_desc': 'Play Store वर रेटिंग द्या!',
      'privacy_title': 'गोपनीयता आणि डेटा',
      'privacy_desc': 'सर्व स्कॅन ऑन-डिव्हाइस प्रोसेस होतात. फोटो कधीही अपलोड होत नाहीत.',
      'about_title': 'PlantGuard बद्दल',
      'about_desc': 'PlantGuard v1.0.0 AI द्वारे पिकांचे रोग ओळखतो. 14 पिकांमध्ये 38+ रोग.',
      'close': 'बंद करा',
      'go_rate': 'रेटिंग द्या',
},
    'kn': {
      'home': 'ಮನೆ',
      'history': 'ಇತಿಹಾಸ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'recent_scans': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
      'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'scan_leaf': 'ಎಲೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'disease_info': 'ರೋಗದ ಮಾಹಿತಿ',
      'crop_tips': 'ಬೆಳೆ ಸಲಹೆಗಳು',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
      'language': 'ಭಾಷೆ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'location': 'ಸ್ಥಳ',
      'offline_mode': 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
      'log_out': 'ಲಾಗ್ ಔಟ್',
      'diagnosis': 'ರೋಗನಿರ್ಣಯ',
      'symptoms': 'ಲಕ್ಷಣಗಳು',
      'treatment': 'ಚಿಕಿತ್ಸೆ',
      'prevention': 'ತಡೆಗಟ್ಟುವಿಕೆ',
      'take_photo': 'ಫೋಟೋ ತೆಗೆಯಿರಿ ಮತ್ತು ರೋಗ ಪತ್ತೆ ಮಾಡಿ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'scans_done': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗಿದೆ',
      'crops_helped': 'ಸಹಾಯವಾದ ಬೆಳೆಗಳು',
      'crops_grown': 'ಬೆಳೆದ ಬೆಳೆಗಳು',
      'my_crops': 'ನನ್ನ ಬೆಳೆಗಳು',
      'status': 'ಸ್ಥಿತಿ',
      'healthy': 'ಆರೋಗ್ಯಕರ',
      'diseased': 'ರೋಗಗ್ರಸ್ತ',
      'unknown': 'ತಿಳಿದಿಲ್ಲ',
          'rate_app': 'PlantGuard ರೇಟ್ ಮಾಡಿ',
      'rate_app_sub': 'ರೈತರಿಗೆ ಸಹಾಯ ಮಾಡಿ',
      'privacy_data': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಡೇಟಾ',
      'privacy_data_sub': 'ಫೋಟೋಗಳು ಫೋನ್ ಬಿಡುವುದಿಲ್ಲ',
      'about_app': 'PlantGuard ಬಗ್ಗೆ',
      'about_app_sub': 'v1.0.0 • DeepCognix AI Labs',
      'offline_mode_sub': 'ಆನ್-ಡಿವೈಸ್ AI • ಇಂಟರ್ನೆಟ್ ಬೇಡ',
      'notif_sub': 'ರೋಗ ಮತ್ತು ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು',
      'location_label': 'ಸ್ಥಳ',
      'offline_title': 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
      'offline_desc': 'PlantGuard ಸಂಪೂರ್ಣ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ. ನಿಮ್ಮ ಡೇಟಾ ಫೋನ್ ಬಿಡುವುದಿಲ್ಲ.',
      'rate_title': 'PlantGuard ಇಷ್ಟವಾಯಿತೇ?',
      'rate_desc': 'Play Store ನಲ್ಲಿ ರೇಟ್ ಮಾಡಿ!',
      'privacy_title': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಡೇಟಾ',
      'privacy_desc': 'ಎಲ್ಲ ಸ್ಕ್ಯಾನ್‌ಗಳು ಡಿವೈಸ್‌ನಲ್ಲೇ ಪ್ರಕ್ರಿಯೆಗೊಳ್ಳುತ್ತವೆ. ಫೋಟೋಗಳು ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ.',
      'about_title': 'PlantGuard ಬಗ್ಗೆ',
      'about_desc': 'PlantGuard v1.0.0 AI ಮೂಲಕ ಸಸ್ಯ ರೋಗ ಪತ್ತೆ ಮಾಡುತ್ತದೆ. 14 ಬೆಳೆಗಳಲ್ಲಿ 38+ ರೋಗಗಳು.',
      'close': 'ಮುಚ್ಚಿ',
      'go_rate': 'ರೇಟ್ ಮಾಡಿ',
},
    'te': {
      'home': 'హోమ్',
      'history': 'చరిత్ర',
      'profile': 'ప్రొఫైల్',
      'recent_scans': 'ఇటీవలి స్కాన్‌లు',
      'see_all': 'అన్నీ చూడండి',
      'scan_leaf': 'ఆకును స్కాన్ చేయండి',
      'disease_info': 'వ్యాధి సమాచారం',
      'crop_tips': 'పంట చిట్కాలు',
      'edit_profile': 'ప్రొఫైల్ సవరించు',
      'language': 'భాష',
      'notifications': 'నోటిఫికేషన్‌లు',
      'location': 'ప్రాంతం',
      'offline_mode': 'ఆఫ్‌లైన్ మోడ్',
      'log_out': 'లాగ్ అవుట్',
      'diagnosis': 'వ్యాధి నిర్ధారణ',
      'symptoms': 'లక్షణాలు',
      'treatment': 'చికిత్స',
      'prevention': 'నివారణ',
      'take_photo': 'ఫోటో తీసి వ్యాధిని గుర్తించండి',
      'gallery': 'గ్యాలరీ',
      'scans_done': 'స్కాన్‌లు పూర్తి',
      'crops_helped': 'సహాయపడిన పంటలు',
      'crops_grown': 'పండించిన పంటలు',
      'my_crops': 'నా పంటలు',
      'status': 'స్థితి',
      'healthy': 'ఆరోగ్యంగా ఉంది',
      'diseased': 'వ్యాధి సోకింది',
      'unknown': 'తెలియదు',
          'rate_app': 'PlantGuard రేటింగ్ ఇవ్వండి',
      'rate_app_sub': 'రైతులకు సహాయపడండి',
      'privacy_data': 'గోప్యత మరియు డేటా',
      'privacy_data_sub': 'ఫోటోలు ఫోన్ వదలవు',
      'about_app': 'PlantGuard గురించి',
      'about_app_sub': 'v1.0.0 • DeepCognix AI Labs',
      'offline_mode_sub': 'ఆన్-డివైస్ AI • ఇంటర్నెట్ అవసరం లేదు',
      'notif_sub': 'వ్యాధి మరియు వాతావరణ హెచ్చరికలు',
      'location_label': 'ప్రాంతం',
      'offline_title': 'ఆఫ్‌లైన్ మోడ్',
      'offline_desc': 'PlantGuard పూర్తిగా ఆఫ్‌లైన్‌లో పనిచేస్తుంది. మీ డేటా ఫోన్ వదలదు.',
      'rate_title': 'PlantGuard నచ్చిందా?',
      'rate_desc': 'Play Store లో రేటింగ్ ఇవ్వండి!',
      'privacy_title': 'గోప్యత మరియు డేటా',
      'privacy_desc': 'అన్ని స్కాన్‌లు పరికరంలోనే ప్రాసెస్ అవుతాయి. ఫోటోలు అప్‌లోడ్ కావు.',
      'about_title': 'PlantGuard గురించి',
      'about_desc': 'PlantGuard v1.0.0 AI తో మొక్కల వ్యాధులు గుర్తిస్తుంది. 14 పంటల్లో 38+ వ్యాధులు.',
      'close': 'మూసివేయి',
      'go_rate': 'రేటింగ్ ఇవ్వండి',
},
    'ta': {
      'home': 'முகப்பு',
      'history': 'வரலாறு',
      'profile': 'சுயவிவரம்',
      'recent_scans': 'சமீபத்திய ஸ்கேன்கள்',
      'see_all': 'அனைத்தையும் பார்',
      'scan_leaf': 'இலையை ஸ்கேன் செய்க',
      'disease_info': 'நோய் தகவல்',
      'crop_tips': 'பயிர் குறிப்புகள்',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'language': 'மொழி',
      'notifications': 'அறிவிப்புகள்',
      'location': 'இடம்',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'log_out': 'வெளியேறு',
      'diagnosis': 'நோய் கண்டறிதல்',
      'symptoms': 'அறிகுறிகள்',
      'treatment': 'சிகிச்சை',
      'prevention': 'தடுப்பு முறை',
      'take_photo': 'புகைப்படம் எடுத்து நோய் கண்டறியவும்',
      'gallery': 'கேலரி',
      'scans_done': 'ஸ்கேன் முடிந்தது',
      'crops_helped': 'உதவிய பயிர்கள்',
      'crops_grown': 'வளர்ந்த பயிர்கள்',
      'my_crops': 'என் பயிர்கள்',
      'status': 'நிலை',
      'healthy': 'ஆரோக்கியமானது',
      'diseased': 'நோய் பாதித்தது',
      'unknown': 'தெரியவில்லை',
          'rate_app': 'PlantGuard மதிப்பிடுங்கள்',
      'rate_app_sub': 'விவசாயிகளுக்கு உதவுங்கள்',
      'privacy_data': 'தனியுரிமை மற்றும் தரவு',
      'privacy_data_sub': 'புகைப்படங்கள் போனை விட்டு வெளியேறாது',
      'about_app': 'PlantGuard பற்றி',
      'about_app_sub': 'v1.0.0 • DeepCognix AI Labs',
      'offline_mode_sub': 'ஆன்-டிவைஸ் AI • இணையம் தேவையில்லை',
      'notif_sub': 'நோய் மற்றும் வானிலை எச்சரிக்கைகள்',
      'location_label': 'இடம்',
      'offline_title': 'ஆஃப்லைன் பயன்முறை',
      'offline_desc': 'PlantGuard முழுவதும் ஆஃப்லைனில் செயல்படுகிறது. உங்கள் தரவு போனை விட்டு வெளியேறாது.',
      'rate_title': 'PlantGuard பிடித்ததா?',
      'rate_desc': 'Play Store இல் மதிப்பிடுங்கள்!',
      'privacy_title': 'தனியுரிமை மற்றும் தரவு',
      'privacy_desc': 'அனைத்து ஸ்கேன்களும் சாதனத்திலேயே செயலாக்கப்படுகின்றன. புகைப்படங்கள் பதிவேற்றப்படாது.',
      'about_title': 'PlantGuard பற்றி',
      'about_desc': 'PlantGuard v1.0.0 AI மூலம் தாவர நோய்களை கண்டறிகிறது. 14 பயிர்களில் 38+ நோய்கள்.',
      'close': 'மூடு',
      'go_rate': 'மதிப்பிடுக',
    },
    'es': {
      'home': 'Inicio',
      'history': 'Historial',
      'profile': 'Perfil',
      'recent_scans': 'Escaneos Recientes',
      'see_all': 'Ver todo',
      'scan_leaf': 'Escanear Hoja',
      'disease_info': 'Info de Enfermedad',
      'crop_tips': 'Consejos de Cultivo',
      'edit_profile': 'Editar Perfil',
      'language': 'Idioma',
      'notifications': 'Notificaciones',
      'location': 'Ubicacion',
      'offline_mode': 'Modo Sin Internet',
      'log_out': 'Cerrar Sesion',
      'diagnosis': 'Diagnostico',
      'symptoms': 'Sintomas',
      'treatment': 'Tratamiento',
      'prevention': 'Prevencion',
      'take_photo': 'Tomar Foto y Diagnosticar',
      'gallery': 'Galeria',
      'scans_done': 'Escaneos',
      'crops_helped': 'Cultivos Ayudados',
      'crops_grown': 'Cultivos Sembrados',
      'my_crops': 'Mis Cultivos',
      'status': 'Estado',
      'healthy': 'Saludable',
      'diseased': 'Enfermo',
      'unknown': 'Desconocido',
      'rate_app': 'Calificar PlantGuard',
      'rate_app_sub': 'Ayuda a los agricultores',
      'privacy_data': 'Privacidad y Datos',
      'privacy_data_sub': 'Las fotos no salen del telefono',
      'about_app': 'Acerca de PlantGuard',
      'about_app_sub': 'v1.0.0 - DeepCognix AI Labs',
      'offline_mode_sub': 'IA en dispositivo - sin internet',
      'notif_sub': 'Alertas de enfermedades y clima',
      'location_label': 'Ubicacion',
      'offline_title': 'Modo Sin Internet',
      'offline_desc': 'PlantGuard funciona sin internet. Tus datos nunca salen del telefono.',
      'rate_title': 'Que tal PlantGuard?',
      'rate_desc': 'Por favor califiquenos en Play Store!',
      'privacy_title': 'Privacidad y Datos',
      'privacy_desc': 'Todos los escaneos se procesan en el dispositivo sin subir fotos.',
      'about_title': 'Acerca de PlantGuard',
      'about_desc': 'PlantGuard v1.0.0 detecta enfermedades en 14 cultivos con 38+ clases.',
      'close': 'Cerrar',
      'go_rate': 'Calificar',
    }
  };

  String t(String key) {
    return _translations[_currentLang]?[key] ?? _translations['en']?[key] ?? key;
  }
}
