import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _currentLang = 'en';
  String get currentLang => _currentLang;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString('ui_lang') ?? 'en';
    notifyListeners();
  }

  Future<void> changeLanguage(String lang) async {
    _currentLang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('ui_lang', lang);
    notifyListeners();
  }

  static const _translations = {
    'en': {
      'home': 'Home',
      'history': 'History',
      'profile': 'Profile',
      'recent_scans': 'Recent Scans',
      'see_all': 'See all',
      'scan_leaf': 'Scan Leaf',
      'disease_info': 'Disease Info',
      'crop_tips': 'Crop Tips',
      'edit_profile': 'Edit Profile',
      'language': 'Language',
      'notifications': 'Notifications',
      'location': 'Location',
      'offline_mode': 'Offline Mode',
      'log_out': 'Log Out',
      'diagnosis': 'Diagnosis',
      'symptoms': 'Symptoms',
      'treatment': 'Treatment',
      'prevention': 'Prevention',
      'take_photo': 'Take Photo & Diagnose',
      'gallery': 'Gallery',
      'scans_done': 'Scans Done',
      'crops_helped': 'Crops Helped',
      'crops_grown': 'Crops Grown',
      'my_crops': 'My Crops',
      'status': 'Status',
      'healthy': 'Healthy',
      'diseased': 'Diseased',
      'unknown': 'Unknown',
    },
    'hi': {
      'home': 'होम',
      'history': 'इतिहास',
      'profile': 'प्रोफ़ाइल',
      'recent_scans': 'हाल के स्कैन',
      'see_all': 'सभी देखें',
      'scan_leaf': 'पत्ती स्कैन करें',
      'disease_info': 'रोग की जानकारी',
      'crop_tips': 'फसल टिप्स',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'location': 'स्थान',
      'offline_mode': 'ऑफलाइन मोड',
      'log_out': 'लॉग आउट',
      'diagnosis': 'निदान',
      'symptoms': 'लक्षण',
      'treatment': 'उपचार',
      'prevention': 'रोकथाम',
      'take_photo': 'फोटो लें और निदान करें',
      'gallery': 'गैलरी',
      'scans_done': 'कुल स्कैन',
      'crops_helped': 'मदद की गई फसलें',
      'crops_grown': 'उगाई गई फसलें',
      'my_crops': 'मेरी फसलें',
      'status': 'स्थिति',
      'healthy': 'स्वस्थ',
      'diseased': 'रोगग्रस्त',
      'unknown': 'अज्ञात',
    },
    'mr': {
      'home': 'होम',
      'history': 'इतिहास',
      'profile': 'प्रोफाईल',
      'recent_scans': 'अलीकडील स्कॅन',
      'see_all': 'सर्व पहा',
      'scan_leaf': 'पान स्कॅन करा',
      'disease_info': 'रोगाची माहिती',
      'crop_tips': 'पीक टिप्स',
      'edit_profile': 'प्रोफाईल संपादित करा',
      'language': 'भाषा',
      'notifications': 'सूचना',
      'location': 'स्थान',
      'offline_mode': 'ऑफलाईन मोड',
      'log_out': 'लॉग आउट',
      'diagnosis': 'निदान',
      'symptoms': 'लक्षणे',
      'treatment': 'उपचार',
      'prevention': 'प्रतिबंध',
      'take_photo': 'फोटो घ्या आणि निदान करा',
      'gallery': 'गॅलरी',
      'scans_done': 'केलेले स्कॅन',
      'crops_helped': 'मदद केलेली पिके',
      'crops_grown': 'लागवड केलेली पिके',
      'my_crops': 'माझी पिके',
      'status': 'स्थिती',
      'healthy': 'निरोगी',
      'diseased': 'रोगट',
      'unknown': 'अज्ञात',
    },
    'kn': {
      'home': 'ಮನೆ',
      'history': 'ಇತಿಹಾಸ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'recent_scans': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
      'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'scan_leaf': 'ಎಲೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'disease_info': 'ರೋಗದ ಮಾಹಿತಿ',
      'crop_tips': 'ಬೆಳೆ ಸಲಹೆಗಳು',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
      'language': 'ಭಾಷೆ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'location': 'ಸ್ಥಳ',
      'offline_mode': 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
      'log_out': 'ಲಾಗ್ ಔಟ್',
      'diagnosis': 'ರೋಗನಿರ್ಣಯ',
      'symptoms': 'ಲಕ್ಷಣಗಳು',
      'treatment': 'ಚಿಕಿತ್ಸೆ',
      'prevention': 'ತಡೆಗಟ್ಟುವಿಕೆ',
      'take_photo': 'ಫೋಟೋ ತೆಗೆಯಿರಿ ಮತ್ತು ರೋಗ ಪತ್ತೆ ಮಾಡಿ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'scans_done': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗಿದೆ',
      'crops_helped': 'ಸಹಾಯವಾದ ಬೆಳೆಗಳು',
      'crops_grown': 'ಬೆಳೆದ ಬೆಳೆಗಳು',
      'my_crops': 'ನನ್ನ ಬೆಳೆಗಳು',
      'status': 'ಸ್ಥಿತಿ',
      'healthy': 'ಆರೋಗ್ಯಕರ',
      'diseased': 'ರೋಗಗ್ರಸ್ತ',
      'unknown': 'ತಿಳಿದಿಲ್ಲ',
    },
    'te': {
      'home': 'హోమ్',
      'history': 'చరిత్ర',
      'profile': 'ప్రొఫైల్',
      'recent_scans': 'ఇటీవలి స్కాన్‌లు',
      'see_all': 'అన్నీ చూడండి',
      'scan_leaf': 'ఆకును స్కాన్ చేయండి',
      'disease_info': 'వ్యాధి సమాచారం',
      'crop_tips': 'పంట చిట్కాలు',
      'edit_profile': 'ప్రొఫైల్ సవరించు',
      'language': 'భాష',
      'notifications': 'నోటిఫికేషన్‌లు',
      'location': 'ప్రాంతం',
      'offline_mode': 'ఆఫ్‌లైన్ మోడ్',
      'log_out': 'లాగ్ అవుట్',
      'diagnosis': 'వ్యాధి నిర్ధారణ',
      'symptoms': 'లక్షణాలు',
      'treatment': 'చికిత్స',
      'prevention': 'నివారణ',
      'take_photo': 'ఫోటో తీసి వ్యాధిని గుర్తించండి',
      'gallery': 'గ్యాలరీ',
      'scans_done': 'స్కాన్‌లు పూర్తి',
      'crops_helped': 'సహాయపడిన పంటలు',
      'crops_grown': 'పండించిన పంటలు',
      'my_crops': 'నా పంటలు',
      'status': 'స్థితి',
      'healthy': 'ఆరోగ్యంగా ఉంది',
      'diseased': 'వ్యాధి సోకింది',
      'unknown': 'తెలియదు',
    },
    'ta': {
      'home': 'முகப்பு',
      'history': 'வரலாறு',
      'profile': 'சுயவிவரம்',
      'recent_scans': 'சமீபத்திய ஸ்கேன்கள்',
      'see_all': 'அனைத்தையும் பார்',
      'scan_leaf': 'இலையை ஸ்கேன் செய்க',
      'disease_info': 'நோய் தகவல்',
      'crop_tips': 'பயிர் குறிப்புகள்',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'language': 'மொழி',
      'notifications': 'அறிவிப்புகள்',
      'location': 'இடம்',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'log_out': 'வெளியேறு',
      'diagnosis': 'நோய் கண்டறிதல்',
      'symptoms': 'அறிகுறிகள்',
      'treatment': 'சிகிச்சை',
      'prevention': 'தடுப்பு முறை',
      'take_photo': 'புகைப்படம் எடுத்து நோய் கண்டறியவும்',
      'gallery': 'கேலரி',
      'scans_done': 'ஸ்கேன் முடிந்தது',
      'crops_helped': 'உதவிய பயிர்கள்',
      'crops_grown': 'வளர்ந்த பயிர்கள்',
      'my_crops': 'என் பயிர்கள்',
      'status': 'நிலை',
      'healthy': 'ஆரோக்கியமானது',
      'diseased': 'நோய் பாதித்தது',
      'unknown': 'தெரியவில்லை',
    }
  };

  String t(String key) {
    return _translations[_currentLang]?[key] ?? _translations['en']?[key] ?? key;
  }
}
